// AUTH types
const SET_TOKEN = 'SET_TOKEN'
const SET_AUTH_INFO = 'SET_AUTH_INFO'
const SET_IS_ADMIN = 'SET_IS_ADMIN'
const RESET_AUTH = 'RESET_AUTH'
const RESET_TOKEN = 'RESET_TOKEN'

// USER types
const SET_USER_ID = 'SET_USER_ID'
const SET_USERNAME = 'SET_USERNAME'
const SET_FIRST_NAME = 'SET_FIRST_NAME'
const SET_LAST_NAME = 'SET_LAST_NAME'
const SET_FULLNAME = 'SET_FULLNAME'
const SET_PHONE_NUM = 'SET_PHONE_NUMBER'
const SET_USER_ADDRESSES = 'SET_USER_ADDRESSES'
const SET_USER_ORDERS = 'SET_MY_ORDERS'
const SET_EMAIL = 'SET_EMAIL'
const SET_USER_INFO = 'SET_USER_INFO'
const RESET_USER = 'RESET_USER'

// PRODUCT types
const ADD_PRODUCT = 'ADD_PRODUCT'
const SET_PRODUCTS = 'SET_PRODUCTS'
const SET_PRODUCT_IDS = 'SET_PRODUCT_IDS'
const SET_QUERY_PRODUCTS = 'SET_QUERY_PRODUCTS'
const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

// CART types
const SET_CART_ITEM = 'SET_CART_ITEM'
const ADD_CART_ITEM = 'ADD_CART_ITEM'
const SET_TOTAL = 'SET_TOTAL'
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
const RESET_CART = 'RESET_CART'
const SET_SECRET = 'SET_SECRET'

// ORDER types
const ADD_ORDER = 'ADD_ORDER'
const SET_ORDERS = 'SET_ORDERS'
const REMOVE_ORDER = 'REMOVE_ORDER'

// CUSTOMER types
const ADD_CUSTOMER = 'ADD_CUSTOMER'
const SET_CUSTOMER = 'SET_CUSTOMER'
const SET_CUSTOMERS = 'SET_CUSTOMERS'
const ADD_RECENT_ORDER = 'ADD_RECENT_ORDER'
const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER'

// ADDRESS types
const ADD_ADDRESS = 'ADD_ADDRESS'
const REMOVE_ADDRESS = 'REMOVE_ADDRESS'

// ERRROR types
const SET_ERROR = 'SET_ERROR'

export { 
    SET_TOKEN, SET_AUTH_INFO,
    RESET_AUTH, RESET_TOKEN,
    SET_USER_ID, SET_USERNAME, SET_USER_ORDERS, SET_PRODUCTS, SET_PRODUCT_IDS, SET_QUERY_PRODUCTS, SET_IS_ADMIN,
    SET_FIRST_NAME, SET_LAST_NAME,
    SET_FULLNAME, SET_PHONE_NUM, SET_EMAIL,
    SET_USER_ADDRESSES, SET_USER_INFO, RESET_USER,
    ADD_PRODUCT, REMOVE_PRODUCT, 
    ADD_CART_ITEM, SET_TOTAL, RESET_CART, SET_SECRET,
    SET_CART_ITEM, REMOVE_CART_ITEM,
    ADD_ORDER, SET_ORDERS, ADD_RECENT_ORDER, REMOVE_ORDER,
    ADD_CUSTOMER, SET_CUSTOMER, SET_CUSTOMERS, REMOVE_CUSTOMER,
    ADD_ADDRESS, REMOVE_ADDRESS, SET_ERROR
}